### ISSUE TITLE
App no longer works; upgrade to v8 API

### ISSUE THREAD

**Issue by alizehctl** [ubuntudroid/todoist-gnome-shell-extension#2]
System: Fedora 30, GNOME 3.32

It's been at least a few weeks since the extension hasn't been working. It looks like it's failing to connect to the Todoist API, since it's perpetually stuck on loading.

![image](https://user-images.githubusercontent.com/31581044/66482083-a7697100-eabb-11e9-863c-26bf2a66d0e7.png)

**Comment by alizehctl** [comment]
Update: This extension is using the v7 API, which was deprecated in August.
https://developer.todoist.com/sync/v8

**Comment by ubuntudroid** [comment]
Hi @aadilayub, thanks for reporting this issue. Unfortunately I am not actively working on this extension anymore, nor do I have a Gnome desktop anymore.

However you are very welcome to provide a fix and I'll make sure to merge it ASAP.

**Comment by ubuntudroid** [comment]
Fixed by #3
